### ISSUE TITLE
allow to integrate multiple gitlabs

### ISSUE THREAD

**Issue by kaystrobach** [wemakecustom/gitlab-composer#10]
would be really awesome to change the code to allow access multiple gitlab instances.

IMHO there are several steps to take:

* convert settings file form ini to yaml
* iterate over instances and then repos to get the needed information
* put all the stuff into one file

The yaml file may look like:

```
m4tthumphrey:
  php-gitlab-api:
    instances:
      -
        apiToken: 'ASDFGHJKL12345678'
        endpointUri: 'http://gitlab.example.com/api/v3/'
```
